import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { unzipSync,strFromU8 } from 'fflate';
const output=process.env.ENGINEERING_TEST_OUTPUT||'generated/v3/engineering-workbench/browser';await mkdir(output,{recursive:true});
const data=JSON.parse(await readFile('apps/workbench/public/engineering.json','utf8'));
const generation=JSON.parse(await readFile('generated/v3/blueprints/generation.json','utf8'));assert.equal(generation.complete,true);const pageCount=generation.pages.length;
const sources={};for(const directory of ['apps/workbench/src','hardware/v3/engineering']){const {readdir}=await import('node:fs/promises');for(const name of await readdir(directory)){if(/\.(js|css|json)$/.test(name))sources[directory+'/'+name]=createHash('sha256').update(await readFile(directory+'/'+name)).digest('hex');}}
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true}),page=await context.newPage(),checks=[],errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(process.env.WORKBENCH_URL||'http://127.0.0.1:5173/')&&!/^(data:|blob:)/.test(r.url()))external.push(r.url());});
const check=n=>{checks.push(n);console.log('PASS',n);};
async function download(selector){const pending=page.waitForEvent('download',{timeout:120000});await page.locator(selector).click();const d=await pending,s=await d.createReadStream(),chunks=[];for await(const c of s)chunks.push(c);return Buffer.concat(chunks);}
try {
 await page.goto(process.env.WORKBENCH_URL||'http://127.0.0.1:5173/');await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});
 await page.locator('[data-mode="drawing"]').click();assert.ok(await page.locator('#engineering-blueprints').isVisible());assert.equal(await page.locator('[data-blueprint-id]').count(),pageCount);check('fixed blueprint catalog defaults to all complete pages');
 await page.locator('[data-blueprint-id="A04"]').click();const svg=await page.locator('.blueprint-paper').innerHTML();assert.match(svg,/data-section-part/);assert.match(svg,/fill-rule="evenodd"/);assert.match(svg,/data:font\/otf;base64/);await page.screenshot({path:output+'/window-section.png'});check('actual closed CAD sections use clipped even-odd hatching and embedded CJK');
 const svgFile=await download('[data-blueprint-export="svg"]');assert.match(svgFile.toString(),/fixedPose/);assert.match(svgFile.toString(),/referenceExcluded/);
 await page.locator('[data-mode="studio"]').click();await page.locator('[data-pose="open"]').click();await page.locator('[data-tab="display"]').click();await page.locator('[data-setting="phone"]').uncheck();await page.locator('[data-setting="card"]').uncheck();await page.locator('[data-hide="lid"]').click({force:true});
 await page.locator('[data-mode="drawing"]').click();assert.equal(await page.locator('.blueprint-paper').innerHTML(),svg);check('standard blueprint bytes remain identical after preview pose, hide and reference changes');
 const png=await download('[data-blueprint-export="png"]');assert.equal(png.readUInt32BE(16),3840);assert.equal(png.readUInt32BE(20),2715);await writeFile(output+'/A04.png',png);check('fixed blueprint PNG exports at 3840×2715');
 const popupPromise=page.waitForEvent('popup');await page.locator('[data-blueprint-export="print"]').click();const popup=await popupPromise;await popup.waitForSelector('svg');await popup.evaluate(()=>document.fonts.ready);const pdf=await popup.pdf({preferCSSPageSize:true,printBackground:true});await writeFile(output+'/A04.pdf',pdf);assert.equal(pdf.subarray(0,4).toString(),'%PDF');await popup.close();check('A3 PDF uses the complete fixed page and embedded local font');
 const archive=unzipSync(await download('[data-blueprint-export="zip"]'));assert.equal(Object.keys(archive).filter(k=>/^drawings\/.*\.svg$/.test(k)).length,pageCount);assert.ok(archive['lists/complete-bom.csv']);assert.ok(archive['fonts/LICENSE-Noto-CJK.txt']);assert.ok(archive['source-fingerprints.json']);assert.ok(archive['assembly-printable.html']);const catalog=JSON.parse(strFromU8(archive['catalog.json']));assert.equal(catalog.cadFingerprint,data.cadFingerprint);assert.equal(catalog.pages.length,pageCount);check('frozen full ZIP covers catalog pages, full BOM, print/tool lists, assembly and source hashes');
 const factory=await download('[data-blueprint-export="acrylic-svg"]');assert.match(factory.toString(),/width="149" height="82"/);assert.match(factory.toString(),/M10,110H110/);const dxf=await download('[data-blueprint-export="acrylic-dxf"]');assert.match(dxf.toString(),/\$INSUNITS\r\n70\r\n4/);assert.match(dxf.toString(),/LWPOLYLINE/);check('1:1 acrylic SVG/DXF retain nominal rectangle and 100mm calibration');
 await page.locator('[data-mode="assembly"]').click();assert.equal(await page.locator('canvas[aria-label]').count(),1);assert.equal(await page.locator('[data-assembly-step]').count(),27);assert.equal(await page.locator('[data-assembly-action="complete"]').isDisabled(),true);check('independent assembly mode reuses one renderer and includes 27 steps');
 await page.locator('[data-assembly-action="play"]').click();await page.waitForTimeout(4500);assert.match(await page.locator('.assembly-summary').textContent(),/^0 \/ 27/);assert.equal(await page.locator('[data-assembly-action="complete"]').isDisabled(),true);check('animation completion never checks or completes physical acceptance');
 for(const box of await page.locator('[data-assembly-check]').all())await box.check();await page.locator('[data-assembly-action="complete"]').click();await page.locator('[data-assembly-note]').fill('首件：仅记录测试，不代表实物通过');await page.reload();await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});await page.locator('[data-mode="assembly"]').click();assert.match(await page.locator('.assembly-summary').textContent(),/^1 \/ 27/);assert.equal(await page.locator('[data-assembly-note]').inputValue(),'首件：仅记录测试，不代表实物通过');check('manual checks, completion, notes and current step survive local reload');
 await page.locator('[data-assembly-step="M03"]').click();await page.locator('[data-assembly-timeline]').fill('500');assert.match(await page.locator('.assembly-animation-label').textContent(),/几何核对路径/);await page.screenshot({path:output+'/keeper-path.png'});await page.locator('[data-mode="studio"]').click();assert.match(await page.locator('#pose-badge').textContent(),/14.0/);assert.equal(await page.locator('[data-setting="phone"]').isChecked(),true);await page.locator('[data-mode="assembly"]').click();assert.match(await page.locator('.assembly-detail h2').textContent(),/^M03/);assert.match(await page.locator('.assembly-percent').textContent(),/50/);check('verified path seeking, tab cancellation and preview pose/reference restoration');
 const stepImage=await download('[data-assembly-action="image"]');assert.equal(stepImage.readUInt32BE(16),2560);assert.equal(stepImage.readUInt32BE(20),1530);await writeFile(output+'/M03.png',stepImage);check('assembly PNG exports its own scene and version footer independently');
 const progress=JSON.parse((await download('[data-assembly-action="export-progress"]')).toString());assert.equal(progress.schema,1);assert.ok(Object.keys(progress.records).some(k=>k.includes(data.cadFingerprint)));check('versioned progress JSON export preserves CAD and step fingerprints');
 const older=structuredClone(progress);const key=Object.keys(older.records)[0],old=older.records[key];old.cadFingerprint='older-cad';delete older.records[key];older.records[`older-cad:${old.stepVersion}:${old.stepFingerprint}`]=old;await page.locator('.assembly-file').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(older))});await page.waitForFunction(()=>document.querySelector('.assembly-storage').textContent.includes('旧版'));assert.match(await page.locator('.assembly-storage').textContent(),/旧版/);assert.match(await page.locator('.assembly-summary').textContent(),/^1 \/ 27/);check('old CAD records are retained without silently overwriting current manual confirmation');
 await page.locator('.assembly-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('JSON'));assert.match(await page.locator('.assembly-detail h2').textContent(),/^M03/);check('damaged progress JSON preserves the active scene and record');
 await page.locator('[data-assembly-step="S19"]').click();await page.locator('[data-assembly-action="play"]').click();await page.waitForTimeout(250);await page.locator('[data-assembly-step="S05"]').click();await page.waitForTimeout(500);assert.equal(await page.locator('.assembly-percent').textContent(),'0%');await page.locator('[data-assembly-step="M03"]').click();check('rapid step changes cancel old animation state deterministically');
 await page.locator('[data-assembly-drawing="A05"]').click();assert.ok(await page.locator('#engineering-blueprints').isVisible());assert.match(await page.locator('.blueprint-status').textContent(),/^A05/);await page.locator('[data-mode="assembly"]').click();await page.locator('[data-assembly-step="S11"]').click();await page.locator('[data-assembly-material="power_board"]').click();assert.ok(await page.locator('#bom-power_board').getAttribute('open')!==null);check('assembly links navigate to fixed blueprint and focused BOM row');
 await page.locator('[data-mode="assembly"]').click();const printPromise=page.waitForEvent('popup');await page.locator('[data-assembly-action="print"]').click();const print=await printPromise;await print.waitForSelector('article');assert.equal(await print.locator('article').count(),27);assert.match(await print.locator('body').textContent(),/待实测/);await print.close();check('printable complete assembly manual has all 27 steps and physical gates');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/mobile-assembly.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-mode="drawing"]').click();await page.locator('[data-engineering-section="blueprints"]').click();await page.screenshot({path:output+'/mobile-blueprints.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);check('mobile assembly and blueprint catalog remain usable without page overflow');
 const blocked=await browser.newContext({viewport:{width:1100,height:900}});await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('denied','SecurityError')}}));const denied=await blocked.newPage();await denied.goto(process.env.WORKBENCH_URL||'http://127.0.0.1:5173/');await denied.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});await denied.locator('[data-mode="assembly"]').click();assert.match(await denied.locator('.assembly-storage').textContent(),/JSON/);await blocked.close();check('denied localStorage leaves assembly guidance and JSON persistence usable');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);check('no browser errors or external runtime requests');
 await writeFile(output+'/results.json',JSON.stringify({pass:true,checks,errors,external,source_sha256:sources,cadFingerprint:data.cadFingerprint,dataFingerprint:data.dataFingerprint},null,2)+'\n');
}catch(e){await writeFile(output+'/results.json',JSON.stringify({pass:false,checks,errors,external,error:String(e),source_sha256:sources},null,2));throw e;}
finally{await browser.close();}
